name: Cypress e2e tests

on: push

jobs:
  Cypress_e2e_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./
  
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Install npm
        working-directory: cypress
        run: npm install cypress --save-dev

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: cypress
          record: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}