name: Cypress e2e Tests

on: [push]

jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v2
        with:
          browser: chrome