name: Cypress e2e tests

on: push

jobs:
  Cypress_e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      
      - name: Install npm
        working-directory: cypress
        run: npm install cypress --save-dev

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: /home/runner/work/Cloud_Resume_FrontEnd/Cloud_Resume_FrontEnd/cypress/e2e/
          spec: e2e/visitorCounter.cy.js
          record: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}